server:
  port: 8181

redis:
  starter: true
  port : 6379
  timeout : 10000 #客户端超时时间单位是毫秒 默认是2000
  maxIdle : 300 #最大空闲数
  maxActive : 120   #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
  maxTotal : 1000   #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
  maxWaitMillis : 1000   #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  minEvictableIdleTimeMillis : 300000  #连接的最小空闲时间 默认1800000毫秒(30分钟)
  numTestsPerEvictionRun : 1024
  timeBetweenEvictionRunsMillis : 30000  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  testOnBorrow :  true
  testOnCreate: true
  testWhileIdle : true
  testOnReturn: true

spring:
  application:
    name: daishu-gateway
  profiles:
    active: @profileActive@
  cloud:
    gateway:
      locator:
        enabled: true
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      # 服务自动发现,取第一个截取词匹配consul
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true #开启根据微服务名称自动转发
          filters:
            - StripPrefix=1
      routes:
      - id: stats
        uri: lb://business
        predicates:
        - Path= /stats/**
      - id: action
        uri: lb://statistics
        predicates:
        - Path= /action/**
youyou:
  jwt:
    active: @profileActive@
    god : false
    tokenCachime: 120
    phpSystemAuthorityUrl: ${youyou.jwt.phpSystemUrl}platform/api/myauthlist
    platformIssuer: daishu_backstage
    stuTokenIssuer: daishu_wxapi
    #免token调用
    excludePatterns :
      /*export* : '.*export.*'
    excludePath :
      #课件
      /statistics/cwAnswerActionServer/answerinput : 'kejian'
      /statistics/cwAnswerActionServer/courseWareQuestion : 'kejian'
      /msg/logs/send/front_log: 'kejian'
      /statistics/homeWorkStuAnswerServer/createPaper: 'kejian'
      /statistics/homeWorkStuAnswerServer/hwAnswerInput: 'kejian'
      #业务系统后台
      /msg/email/send : 'php-back'
      /statistics/enterRoomServer/queryStuLessonEnterRoom: 'php-back'
      /statistics/stuAttendanceServer/queryStuAttendance: 'php-back'
      /statistics/lessonScoreStuServer/queryLessonScoreStuMessage: 'php-back,php-stu'
      /business/lessonCoinBagUseServer/queryUserLessonBag: 'php-back'
      #业务系统学生端
      /statistics/server/repor/learning/unread/list: 'php-stu'
      /statistics/server/repor/learning/list: 'php-stu'
      /business/videoTkyRoomMessageServer/queryTkyGetlogininfoResult: 'php-stu'
      /statistics/satisfactionServer/querySatisfaction: 'php-stu'
       #获取离线视频列表
      /business/videoParseResourceServer/queryParseVideoResource: 'back,stu'
      /business/inClassController/queryNewWorkOrderNum : 'back'
    includePath :
      /business/conponController/insertConpon : 'back'
      /business/conponController/modifyConpon : 'back'
      /business/conponController/queryConponById : 'back'
      /business/conponController/queryCoponPage : 'back'
      /business/conponSentController/importConponUserExcel : 'back'
      /business/conponSentController/queryQueryExcelLogPage : 'back'
      /business/conponUserController/queryConponUserPage : 'back'
      /business/excelGeneralLogController/insertExcel : 'back'
      /business/excelGeneralLogController/queryExcel : 'back'
      /business/inClassController/modifyWorkerOrderFromClaimant : 'back'
      /business/inClassController/modifyWorkerOrderStatus : 'back'
      /business/inClassController/queryClaimedCount : 'back'
      /business/inClassController/queryConfig : 'back'

      /business/inClassController/queryTeacherConfig : 'back'
      /business/inClassController/queryWorkerOrderList : 'back'
      /business/inClassController/queryWorkerOrderStatus : 'back'
      /business/inClassController/workOrder/message/list : 'back'
      /business/inClassController/workOrder/message/tota : 'back'
      /business/innerWorkerStaticalController/queryInnerWorkerStatical : 'back'
      /business/innerWorkerStaticalController/querySecondWorkerOrder : 'back'
      /business/innerWorkerStaticalController/queryWorkerOrderStaticalPage : 'back'
      /business/lessonBagController/get : 'back'
      /business/lessonBagController/list : 'back'
      /business/lessonBagController/create: 'back'
      /business/lessonBagController/update: 'back'
      /business/lessonBagController/delete: 'back'
      /business/lessonCoinSentController/importLessonCoinExcel : 'back'
      /business/lessonCoinSentController/initMq : 'back'
      /business/lessonCoinSentController/queryLessonCoinExcelPage : 'back'
      /business/lessonCoinSentController/queryLessonCoinSentExcelLog : 'back'
      /business/lessonCoinSentDetailController/queryLessonCoinSentDetailPage : 'back'
      /business/macroWorkerStatisticalController/queryMacroWorker : 'back'
      /business/macroWorkerStatisticalController/queryMacroWorkerLogin : 'back'
      /business/productionWorkerOrderController/insertInClassWorkerOrder : 'back'
      /business/productionWorkerOrderController/queryMappingIdByPhone : 'back'
      /business/productionWorkerOrderController/queryProductionMyCount : 'back'
      /business/stuLessonDetailController/modifyOutLineTypeAllowed : 'back'
      /business/stuNewsController/queryMessageNum : 'back'
      /business/stuNewsController/queryStuNewsList : 'back'
      /business/stuNewsController/updateFollow : 'back'
      /business/lessonStuOpenMicController/queryMaterialInfo : 'back'
      /business/videoParseResourceMaterailServer/queryMaterialTeaVideo : 'back'
      /platform/lessonbag/addOrder : 'back'
      /statistics/hwAnswerController/queryHwAnswer : 'back'
      /statistics/lessonScoreController/queryLessonAction : 'back'
      /statistics/lessonScoreController/queryLessonShow : 'back'
      /statistics/lessonScoreController/queryLessonStatistics : 'back'
      /statistics/lessonScoreController/querySatisfaction : 'back'
      /statistics/lessonScoreStuController/queryLessonScoreStuPage : 'back'
      /statistics/stuAttendanceServer/ : 'back'
      /statistics/tutorController/queryStuByTutor : 'back'
      /statistics/lessonScoreController/queryLessonScorePage : 'back'
      /statistics/audioMaterInfoController/queryList : 'back'
      /statistics/audioMaterialSummaryController/queryTime : 'back'
      /statistics/audioMaterialSummaryController/queryOrder: 'back'
      #上传卡顿信息
      /action/student/lesson/create : 'stu'
      #上传丢包信息
      /action/student/packet/lesson/create : 'stu'
      #AI进入教室心跳
      /statistics/enterRoomServer/reportMessage : 'stu'
      #显示答题/上报答题情况
      /statistics/clickerAnswerServer/insertOrUpdateStudentAnswer: 'stu'
      #新版显示答题/上报答题情况
      /statistics/cwAnswerActionServer/insertClickStuQuestion: 'stu'
      #评价弹窗获取问题列表
      /statistics/satisfactionServer/querySatisfactionConfig: 'stu'
      #提交评价
      /statistics/satisfactionServer/insertSatisfaction: 'stu'
      #获取老师离线视频列表
      /business/videoResourceServer/queryVideoResource: 'stu'

      #下载资源完成后回调
      /business/stuLessonDetailServer/successDown: 'stu'
      #上传回顾日志
      /statistics/lessonReplayServer/insertLessonStuReplayLog: 'stu'
      #开口信息采集
      /statistics/lessonStuOpenMouthServer/insertLog: 'stu'
      #微信
      /statistics/student/repor/learning/get : 'wx'
      /business/stuNewsController/insertSalesNews: 'wx'
      /msg/wxapi/email/sendByGroup: 'wx'
      /business/wxapi/repor/switch: 'wx'
    includePatterns :
      /business/lessonBagController/**  : 'back'
      /stats/api/signup/** : 'back'
      /stats/api/stats/introduce/** : 'back'
      /statistics/platform/stability/** : 'back'
    #accessBlackList:
      #ipaddr:
        #- '192.168.1.1'
      #failurePath:
        #- '/statistics/stuLessonGiftServer/findStuLessonGift'


logging:
  level:
    root: "INFO"
#负载均衡
mybalance:
  open : true
  #灰度
  grayscale:
    - order: -129
      id: ver等于2.0.0的queryPort请求,投射到9091,ver不等于2.0.0的queryPort分发到其他服
      ip: 192.168.0.225:9091
      ver: '=2.0.0'
      url: '/statistics/testServer/queryPort'
      exclusive : 'trueUrl'


