youyou:
  jwt:
    phpSystemUrl: https://zxxb-system-test.100daishu.com/
    platform: testsecret
    student: dspystudent!@#
    teacher: teachersec!@#
    wxapi: wxapisec!@#
---
redis:
  hostName: r-2zespxw0qylqcy6lgf.redis.rds.aliyuncs.com
  password: 494v9UulXc